pair/pair/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("reviews.urls")),
    path("reviews/", include("reviews.urls")),
]

pair/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("write/", views.write, name="write"),
    path("detail/<int:_id>", views.detail, name="detail"),
    path("delete/<int:_id>", views.delete, name="delete"),
    path("update/<int:_id>", views.update, name="update"),
]

pair/reviews/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pair/reviews/views.py
from django.shortcuts import render, redirect
from .models import Review
import datetime

# Create your views here.
def index(request):
    data = Review.objects.all()
    return render(request, "reviews/index.html", {"data": data})


def detail(request, _id):
    data = Review.objects.get(id=_id)

    return render(request, "reviews/detail.html", {"data": data})


def write(request):
    _title = request.GET.get("title")
    _content = request.GET.get("content")

    Review.objects.create(title=_title, content=_content)

    return redirect("reviews:index")


def update(request, _id):
    target = Review.objects.get(id=_id)

    target.title = request.GET.get("title")
    target.content = request.GET.get("content")
    target.updated_at = datetime.date.today()

    target.save()

    return redirect("reviews:detail", _id)


def delete(request, _id):
    Review.objects.get(id=_id).delete()

    return redirect("reviews:index")

pair/pair/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
    {% block content%}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>

pair/reviews/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
    {% block content%}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>

pair/reviews/templates/reviews/detail.html
{% extends 'base.html' %}

{% block content %}

<!-- footer fixed with vh-100 value -->
<div class="container vh-100">
    <div class="row">
        <div class="col-9 mt-5">
            <h1>{{ data.title }}</h1>
            <div>
                <p class="text-black d-block my-2">
                    <span>리뷰 작성 날짜 : {{ data.created_at }}</span>
                </p>
                <p class="text-black d-block my-2">
                    <span">리뷰 수정 날짜 : {{ data.updated_at }}</span>
                </p>
            </div>

            <hr />
            <p>
                {{ data.content }}
            </p>

            <hr class="my-0" />

            <div class="d-flex justify-content-end mt-3 mb-5">
                <button class="btn btn-outline-primary me-3" data-bs-toggle="modal" data-bs-target="#exampleModal">리뷰
                    수정</button>
                <a class="btn btn-outline-danger" href="{% url 'reviews:delete' _id=data.id %}">리뷰 삭제</a>
            </div>

        </div>
    </div>
</div>


<!-- 모달 -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">리뷰 수정</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'reviews:update' data.id %}" method="GET">
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">제목</label>
                        <input type="text" class="form-control" id="recipient-name" name="title"
                            value="{{ data.title }}">
                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">내용</label>
                        <textarea class="form-control" id="message-text" name="content">{{ data.content }}
                            </textarea>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">리뷰 쓰기</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

pair/reviews/templates/reviews/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-3 mb-5">

    <div class="row">
        <table class="table align-middle text-center mt-3">
            <thead>
                <tr>
                    <th scope="col">리뷰 번호</th>
                    <th scope="col">리뷰 제목</th>
                    <th scope="col">작성 시간</th>
                    <th scope="col">수정 시간</th>
                </tr>
            </thead>
            <tbody>
                {% for i in data %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a class="text-decoration-none" href="{% url 'reviews:detail' _id=i.id %}">{{ i.title }}</a>
                    </td>
                    <td>{{ i.created_at }}</td>
                    <td>{{ i.updated_at }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="d-flex justify-content-end px-0 py-3 mb-3">
            <button class="btn fw-bold" data-bs-toggle="modal" data-bs-target="#exampleModal">리뷰 작성</button>
        </div>
    </div>
</div>

<!-- 모달 -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">리뷰 작성</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="/reviews/write" method="GET">
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">제목</label>
                        <input type="text" class="form-control" id="recipient-name" name="title">
                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">내용</label>
                        <textarea class="form-control" id="message-text" name="content"></textarea>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">리뷰 쓰기</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}